# Generated by Django 4.0.6 on 2024-12-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=255)),
                ('key_skills', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VacancyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.CharField(help_text='Unique ID for the vacancy from the API', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_skills', models.TextField(blank=True, help_text='Comma-separated list of skills', null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('region', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_by_city', to='profession.profession')),
            ],
            options={
                'ordering': ['-share'],
            },
        ),
        migrations.CreateModel(
            name='SalaryByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_by_city', to='profession.profession')),
            ],
            options={
                'ordering': ['-avg_salary'],
            },
        ),
    ]
